### ISSUE TITLE
Problems with slashes in parameters

### ISSUE THREAD

**Issue by javiquinte** [javiquinte/provgen#14]
The output from the system, as it was, was not validating at http://ttl.summerofcode.be/
The problem was the iRODS path, which included at least a slash. In order to overcome this I escaped the strings to use in the replacement, but that did not always work. For instance, after commit 40ecd68fa6220c7435b134b00d5af9342ceb9faf the datetime type was not validating because the ":" character was also being escaped.
Since commit 1dca00a7b9c5d991e90d569e094ac7f5b9f414f7 I'm escaping only slashes and _**it validates**_. However, there are probably places where we would like to escape a string and somewhere else not.

For instance, in the first line yes, but in the third one not:

> provgen:mynode.gfz-potsdam.de\/geofonZone\/archive\/myfile.txt
    a prov:Entity;
    rdfs:label "\/geofonZone\/archive\/myfile.txt";

@lindareijnhoudt What do you think? We could have two different prefixes: `EUDAT_LITERAL` to be used in places where the variable should not be escaped and `EUDAT_ESCAPE` for the same content but escaped.

**Comment by lindareijnhoudt** [comment]
yes, that makes sense. would we only need those prefixes in the template? in that case, the calling function does not have to add it twice?

**Comment by javiquinte** [comment]
Sure! I already implemented it in commit 92c7b563ab7a7837f2f45b429ecc9d32505aa1b0
I'll try to generate the records for Vasily.
